name: Robot Framework Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GEMINI_TOKEN: ${{ secrets.GEMINI_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip curl xvfb libgbm-dev
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -yf
        rm google-chrome-stable_current_amd64.deb

    - name: Install ChromeDriver
      run: |
        # Fallback method for ChromeDriver installation
        CHROME_MAJOR_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d'.' -f1)
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$((CHROME_MAJOR_VERSION-1))")
        echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"
        
        wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver

    - name: Install Robot Framework and libraries
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install robotframework-requests
        pip install webdriver-manager

    - name: Run tests
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 -ac +extension GLX +render -noreset &
        robot --variable BROWSER:headlesschrome --outputdir ./results tests.robot

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: robot-results
        path: ./results/